name: 'MakerCAD build'
description: 'Build a MakerCAD project'
inputs:
  entry:
    description: The project entry point
    default: 'main.go'
runs:
  using: "composite"
  steps:
    - name: Update apt
      run: sudo apt-get update
      shell: bash
    - name: Install Dependencies 
      run: sudo apt-get install -yq libocct-data-exchange-dev cmake cpp libtbb-dev
      shell: bash
    - name: Get occwrapper
      uses: actions/checkout@v4
      with:
        repository: 'marcuswu/occwrapper'
        # default fetch-depth is insufficent to find previous coverage notes
        fetch-depth: 10
    - name: Build occwrapper
      run: mkdir build && cd build && cmake .. && sudo make install && cd ..
      shell: bash
    - name: Check out model code
    - uses: actions/checkout@v4
      with:
        # default fetch-depth is insufficent to find previous coverage notes
        fetch-depth: 10
    - name: Get dependencies
      run: go mod tidy
      shell: bash
    - name: Run project code
      run: go run ${{ inputs.entry }}
      shell: bash